baseURL = 'https://ourshoes.github.io.git/'
languageCode = 'en-us'
title = 'OurShoes'
theme = 'mykios'
summaryLength = "5"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
